name: show-directory
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v4
      - run: make setup
      - run: make test
      - run: make lint
